// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: stonks/v1/stonk_service.proto

package stonksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStonkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stonk string `protobuf:"bytes,1,opt,name=stonk,proto3" json:"stonk,omitempty"`
}

func (x *GetStonkRequest) Reset() {
	*x = GetStonkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stonks_v1_stonk_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStonkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStonkRequest) ProtoMessage() {}

func (x *GetStonkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stonks_v1_stonk_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStonkRequest.ProtoReflect.Descriptor instead.
func (*GetStonkRequest) Descriptor() ([]byte, []int) {
	return file_stonks_v1_stonk_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetStonkRequest) GetStonk() string {
	if x != nil {
		return x.Stonk
	}
	return ""
}

type GetStonkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Stonk    string `protobuf:"bytes,2,opt,name=stonk,proto3" json:"stonk,omitempty"`
	Buyornot string `protobuf:"bytes,3,opt,name=buyornot,proto3" json:"buyornot,omitempty"`
}

func (x *GetStonkResponse) Reset() {
	*x = GetStonkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stonks_v1_stonk_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStonkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStonkResponse) ProtoMessage() {}

func (x *GetStonkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stonks_v1_stonk_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStonkResponse.ProtoReflect.Descriptor instead.
func (*GetStonkResponse) Descriptor() ([]byte, []int) {
	return file_stonks_v1_stonk_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetStonkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetStonkResponse) GetStonk() string {
	if x != nil {
		return x.Stonk
	}
	return ""
}

func (x *GetStonkResponse) GetBuyornot() string {
	if x != nil {
		return x.Buyornot
	}
	return ""
}

var File_stonks_v1_stonk_service_proto protoreflect.FileDescriptor

var file_stonks_v1_stonk_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x6e,
	0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f,
	0x6e, 0x6b, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f,
	0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x6f, 0x72, 0x6e, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x79, 0x6f, 0x72, 0x6e, 0x6f, 0x74, 0x32, 0x53,
	0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x6f,
	0x6e, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x69, 0x65, 0x74, 0x7a, 0x79, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72,
	0x64, 0x62, 0x6f, 0x74, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x74, 0x6f, 0x6e, 0x6b, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x74, 0x6f, 0x6e, 0x6b, 0x73, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stonks_v1_stonk_service_proto_rawDescOnce sync.Once
	file_stonks_v1_stonk_service_proto_rawDescData = file_stonks_v1_stonk_service_proto_rawDesc
)

func file_stonks_v1_stonk_service_proto_rawDescGZIP() []byte {
	file_stonks_v1_stonk_service_proto_rawDescOnce.Do(func() {
		file_stonks_v1_stonk_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stonks_v1_stonk_service_proto_rawDescData)
	})
	return file_stonks_v1_stonk_service_proto_rawDescData
}

var file_stonks_v1_stonk_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stonks_v1_stonk_service_proto_goTypes = []interface{}{
	(*GetStonkRequest)(nil),  // 0: stonk.v1.GetStonkRequest
	(*GetStonkResponse)(nil), // 1: stonk.v1.GetStonkResponse
}
var file_stonks_v1_stonk_service_proto_depIdxs = []int32{
	0, // 0: stonk.v1.StonkService.GetStonk:input_type -> stonk.v1.GetStonkRequest
	1, // 1: stonk.v1.StonkService.GetStonk:output_type -> stonk.v1.GetStonkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stonks_v1_stonk_service_proto_init() }
func file_stonks_v1_stonk_service_proto_init() {
	if File_stonks_v1_stonk_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stonks_v1_stonk_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStonkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stonks_v1_stonk_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStonkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stonks_v1_stonk_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stonks_v1_stonk_service_proto_goTypes,
		DependencyIndexes: file_stonks_v1_stonk_service_proto_depIdxs,
		MessageInfos:      file_stonks_v1_stonk_service_proto_msgTypes,
	}.Build()
	File_stonks_v1_stonk_service_proto = out.File
	file_stonks_v1_stonk_service_proto_rawDesc = nil
	file_stonks_v1_stonk_service_proto_goTypes = nil
	file_stonks_v1_stonk_service_proto_depIdxs = nil
}
